<a href="https://colab.research.google.com/github/Dracarys38/Knute-homework/blob/main/%22%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B0_4_1_%D0%9F%D0%BE%D1%81%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8F%D0%BA_2_15_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Постельняк Ігор Сергійович ФІТ 2-15

In [ ]:
import numpy as np
np.__version__

'2.0.2'

1. Створи матрицю 3*3, заповни її цілими випадковими числами від 1 до 5

In [ ]:
matrix = np.random.randint(1, 6, size=(3, 3))
matrix

array([[2, 5, 2],
       [3, 1, 1],
       [3, 2, 3]])

2. Обчислити визначник матриці

In [ ]:
det = np.linalg.det(matrix)
det

np.float64(-22.000000000000004)

3. Знайти добуток всіх елементів матриці

In [ ]:
product = np.prod(matrix)
product

np.int64(1080)

In [ ]:
prod_1= np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3= np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(1080)

4. Знайти суму всіх елементів матриці

In [ ]:
sum = np.sum(matrix)
sum

np.int64(22)

5. Обчислити найбільший, найменший елементи

In [ ]:
max_element = np.max(matrix)
print("Найбільший елемент матриці:", max_element)
min_element = np.min(matrix)
print("Найменший елемент матриці:", min_element)

Найбільший елемент матриці: 5
Найменший елемент матриці: 1


6. Знайти середнє значення елементів матриці

In [ ]:
mean = np.mean (matrix)
print("Середнє значення елементів матриці:", mean)

Середнє значення елементів матриці: 2.4444444444444446


7. Знайти матрицю, що складена з квадратних коренів.

In [ ]:
sqrt_matrix = np.sqrt(matrix)
print("Матриця квадратних коренів:")
print(sqrt_matrix)

Матриця квадратних коренів:
[[1.41421356 2.23606798 1.41421356]
 [1.73205081 1.         1.        ]
 [1.73205081 1.41421356 1.73205081]]


8. Обчислити суму елементів кожного рядка. Відповідь записати як вектор-стовпчик

In [ ]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)
print("Сума елементів кожного рядка:")
print(row_sums)

Сума елементів кожного рядка:
[[9]
 [5]
 [8]]


9. Створити вектор, що містить 25 елементів. Заповнити числами від 0 до 9. Відсортувати числа за спаданням.

In [ ]:
vector = np.random.randint(0, 10, size=25)
print("Початковий вектор:")
print (vector)
sorted_vector = np.sort(vector) [::-1]
print("Вектор після сортування за спаданням:")
print(sorted_vector)

Початковий вектор:
[1 5 9 4 7 1 8 5 6 9 6 5 7 9 6 5 4 4 0 2 2 0 2 4 9]
Вектор після сортування за спаданням:
[9 9 9 9 8 7 7 6 6 6 5 5 5 5 4 4 4 4 2 2 2 1 1 0 0]


10. Знайти моду, медіану, середнє, максимальне, мінімальне значення

In [ ]:
from scipy import stats
mode = stats.mode(vector)
median = np.median(vector)
mean = np.mean (vector)
max_value = np.max(vector)
min_value = np.min(vector)
print("Мода:", mode)
print("Медіана:", median)
print("Середнє:", mean)
print("Максимальне значення:", max_value)
print("Мінімальне значення:", min_value)

Мода: ModeResult(mode=np.int64(4), count=np.int64(4))
Медіана: 5.0
Середнє: 4.8
Максимальне значення: 9
Мінімальне значення: 0


11. Створити дві матриці 4*4, заповнені числами від 1 до 10. Обчислити суму, різницю, поелементний добуток, частку.

In [ ]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

Матриця 1:
[[ 9  2  3  3]
 [ 9  1  9 10]
 [10  9  2  4]
 [ 1  8  8  6]]

Матриця 2:
[[ 8  3  1  7]
 [ 9  8  5  9]
 [10  4  2  8]
 [ 4  7  2  4]]


In [ ]:
matrix_sum = matrix1 + matrix2
matrix_diff = matrix1 - matrix2
matrix_product = matrix1 * matrix2
print("\nСума матриць:")
print(matrix_sum)
print("\nРізниця матриць:")
print(matrix_diff)
print("\nПоелементний добуток матриць:")
print(matrix_product)


Сума матриць:
[[17  5  4 10]
 [18  9 14 19]
 [20 13  4 12]
 [ 5 15 10 10]]

Різниця матриць:
[[ 1 -1  2 -4]
 [ 0 -7  4  1]
 [ 0  5  0 -4]
 [-3  1  6  2]]

Поелементний добуток матриць:
[[ 72   6   3  21]
 [ 81   8  45  90]
 [100  36   4  32]
 [  4  56  16  24]]


12. Задати вектор-рядок, що містить дійсні числа 1.0-8.0. Зробити матрицю 3*3. Помножити на вектор-рядок, що містить числа 0.0-2.0

In [ ]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
x1 = x.reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
x2 = np.arange(3.0)
x2

array([0., 1., 2.])

In [ ]:
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

13. Задати вектор-рядок (числа 1-5). Обчислити вектор в кубі.

In [ ]:
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.power (x1, 3)

array([  0,   1,   8,  27,  64, 125])

14. Піднести до ступеня

In [ ]:
x2= np.array([1, 2, 3, 3, 2, 1])
x1 = np.arange(6)
x1 ** x2

array([ 0,  1,  8, 27, 16,  5])